In [1]:
import numpy as np

In [22]:
M = np.array([[1,2],[3,4]])
M

array([[11, 12],
       [21, 22]])

In [32]:
A = np.array([[1,1],[0,1]])
A

array([[1, 1],
       [0, 1]])

In [39]:
np.einsum("ij,kl->ijkl", M, M)

array([[[[121, 132],
         [231, 242]],

        [[132, 144],
         [252, 264]]],


       [[[231, 252],
         [441, 462]],

        [[242, 264],
         [462, 484]]]])